<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE collection[
    <!ELEMENT collection (description, recipe)>
    <!ELEMENT description (#PCDATA)>
    <!ELEMENT recipe (title, ingredient+, preparation, comment, nutrition)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT ingredient EMPTY>
    <!ATTLIST ingredient name CDATA #REQUIRED>
    <!ATTLIST ingredient amount CDATA #IMPLIED>
    <!ATTLIST ingredient unit CDATA #IMPLIED>
    <!ELEMENT preparation (step+)>
    <!ELEMENT step (#PCDATA)>
    <!ELEMENT comment (#PCDATA)>
    <!ELEMENT nutrition EMPTY>
    <!ATTLIST nutrition calories CDATA #REQUIRED>
    <!ATTLIST nutrition fat CDATA #REQUIRED>
    <!ATTLIST nutrition carbohydrates CDATA #REQUIRED>
    <!ATTLIST nutrition protein CDATA #REQUIRED>
]>
<collection>
    <description>Some delicious recipes for our students.</description>
    <recipe>
        <title>Beef Parmesan with Garlic Angel Hair Pasta</title>
        <ingredient name="Beef steak" amount="0.7" unit="kg"/>
        <ingredient name="Parmesan" amount="200" unit="gr"/>
        <ingredient name="Garlic" amount="5" unit="pieces"/>
        <ingredient name="Savory" amount="20" unit="gr"/>
        <ingredient name="Olive oil" amount="4" unit="spoons"/>
        <ingredient name="Salt"/>
        <preparation>
            <step>Preheat oven to 175 degrees C.</step>
            <step>Mix all the products. Add salt according your flavor.</step>
            <step>Bake 50 min. without cover.</step>
        </preparation>
        <comment>Optional comment:Make the meat ahead of time, and refrigerate over night. Save themozzarella till the last minute.
        </comment>
        <nutrition calories="1264" fat="28" carbohydrates="43" protein="35"/>
    </recipe>
</collection>